spring:
  application:
    name: api-store
  datasource:
    url: jdbc:postgresql://localhost:5432/store-db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migrations