spring:
  application:
    name: api-store
  datasource:
    url: jdbc:postgresql://localhost:5432/store-db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mvc:
    problemdetails:
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org:
      flywaydb: DEBUG